#!/usr/bin/env bash
# svc-scripts 0.1.1 — canonical copy: agollum/docker/services/
# Edit there and copy the whole set across; svc-compose.sh is sourced by
# the others, so a half-updated set breaks in ways that look like a bug.
# Render NanoMQ's generated config (password file + ACL) from .env before the
# broker starts.
#
# NanoMQ has no env templating, so its account passwords and its ACL usernames
# cannot come from the process environment the way api/nexus read theirs. This
# renders both files from the MQTT_* values in .env — one source of truth:
#
#   nanomq_pwd.conf  <- MQTT_{,NODE_,VIEWER_}USER / _PASSWORD  (account passwords)
#   nanomq_acl.conf  <- the *_USER names substituted into nanomq_acl.conf.example
#
# Both generated files are gitignored (only the .example templates are committed),
# so on a fresh clone they DO NOT EXIST. If the broker starts before they are
# generated, docker bind-mounts an empty DIRECTORY in place of each missing file
# and nanomq dies in a crash loop with "input in flex scanner failed". svc-start.sh
# calls this first to prevent exactly that; this script also clears any such stub
# directory it finds, so the failure cannot recur even after a bad start.
#
# No-op (exit 0) in a repo with no nanomq config. Handles both the provider layout
# (./nanomq) and the public-backing layout (./public/nanomq).
#
# Idempotent. Safe to run by hand:  ./svc-gen-nanomq.sh
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env}"

svc_log() { printf '[gen-nanomq] %s\n' "$*"; }
die()     { printf '[gen-nanomq] FATAL: %s\n' "$*" >&2; exit 1; }

# Read ONE key from the compose .env. LAST assignment wins (compose is last-wins),
# strips a single surrounding quote pair, and un-doubles '$$' -> '$' so the value
# equals exactly what compose interpolates into the app clients and the SPA — the
# broker password MUST equal what the clients dial with.
read_env() { # <KEY> -> raw value, or returns 1 if absent
  local key="$1" line val
  line="$(grep -E "^${key}=" "$ENV_FILE" | tail -n1)" || true
  [[ -n "$line" ]] || return 1
  val="${line#*=}"
  if [[ ${#val} -ge 2 ]]; then
    case "$val" in
      \"*\") val="${val:1:${#val}-2}" ;;
      \'*\') val="${val:1:${#val}-2}" ;;
    esac
  fi
  val="${val//\$\$/\$}"
  printf '%s' "$val"
}

require() { # <KEY> -> value or die (empty / placeholder both fail)
  local key="$1" val
  val="$(read_env "$key")" || die "$key is not set in $ENV_FILE"
  [[ -n "$val" ]] || die "$key is empty in $ENV_FILE"
  case "$val" in replace*) die "$key still holds a placeholder in $ENV_FILE" ;; esac
  printf '%s' "$val"
}

gen_pwd() { # <nanomq-dir> — HOCON "username: password" pairs; secret, 0600
  local out="$1/nanomq_pwd.conf" su sp nu np vu vp
  su="$(require MQTT_USER)";        sp="$(require MQTT_PASSWORD)"
  nu="$(require MQTT_NODE_USER)";   np="$(require MQTT_NODE_PASSWORD)"
  vu="$(require MQTT_VIEWER_USER)"; vp="$(require MQTT_VIEWER_PASSWORD)"
  ( umask 077
    cat > "$out" <<EOF
# GENERATED by svc-gen-nanomq.sh from .env — DO NOT EDIT, DO NOT COMMIT.
# NanoMQ password file: HOCON "username: password" pairs, included by nanomq.conf
# -> auth.password. Roles/ACL: nanomq_acl.conf. Regenerated on every bring-up.
#   service (api, nexus)      — MQTT_USER        / MQTT_PASSWORD
#   node    (device firmware) — MQTT_NODE_USER   / MQTT_NODE_PASSWORD
#   viewer  (browsers)        — MQTT_VIEWER_USER / MQTT_VIEWER_PASSWORD
${su}: ${sp}
${nu}: ${np}
${vu}: ${vp}
EOF
  ) || die "could not write $out"
  svc_log "wrote $out (accounts: $su, $nu, $vu)"
}

gen_acl() { # <nanomq-dir> — usernames substituted into nanomq_acl.conf.example
  local tmpl="$1/nanomq_acl.conf.example" out="$1/nanomq_acl.conf" su nu vu v
  [[ -f "$tmpl" ]] || die "$tmpl not found (needed to render the ACL)"
  su="$(require MQTT_USER)"; nu="$(require MQTT_NODE_USER)"; vu="$(require MQTT_VIEWER_USER)"
  # A username with an ACL/JSON metacharacter would corrupt or, worse, widen the
  # rules. Restrict to a conservative broker-username charset before sed.
  for pair in "MQTT_USER:$su" "MQTT_NODE_USER:$nu" "MQTT_VIEWER_USER:$vu"; do
    v="${pair#*:}"
    [[ "$v" =~ ^[A-Za-z0-9._-]+$ ]] || die "${pair%%:*}='$v' has characters not allowed in a broker username ([A-Za-z0-9._-])"
  done
  sed -e "s/@SERVICE_USER@/${su}/g" \
      -e "s/@NODE_USER@/${nu}/g" \
      -e "s/@VIEWER_USER@/${vu}/g" \
      "$tmpl" > "$out" || die "could not write $out"
  # A stray token means the template gained a role this script does not fill —
  # fail loud rather than ship a half-substituted ACL.
  if grep -q '@[A-Z_]*_USER@' "$out"; then
    rm -f "$out"
    die "unsubstituted token(s) remain in $out — template has a role svc-gen-nanomq.sh does not fill"
  fi
  svc_log "wrote $out (service=$su, node=$nu, viewer=$vu)"
}

# A nanomq config dir is marked by its committed ACL template. Check both the
# provider (./nanomq) and public-backing (./public/nanomq) layouts.
found=0
for dir in "$SCRIPT_DIR/nanomq" "$SCRIPT_DIR/public/nanomq"; do
  [[ -f "$dir/nanomq_acl.conf.example" ]] || continue
  found=1
  [[ -f "$ENV_FILE" ]] || die "$ENV_FILE not found — run ./svc-build-env.sh first"
  # Clear any empty stub DIRECTORY docker created over a missing generated file on
  # a prior bad start — else the cat/sed below fails writing "a file over a dir".
  for f in nanomq_pwd.conf nanomq_acl.conf; do
    if [[ -d "$dir/$f" ]]; then
      rmdir "$dir/$f" 2>/dev/null || die "$dir/$f is a directory (a docker bind-mount stub) and is not empty — remove it and retry"
      svc_log "cleared empty stub dir $dir/$f (docker created it over the missing file)"
    fi
  done
  gen_pwd "$dir"
  gen_acl "$dir"
done

[[ "$found" -eq 1 ]] || svc_log "no nanomq config in this repo — nothing to generate"
exit 0
